# Generated by Django 3.2 on 2023-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners_images/')),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
    ]
