# Generated by Django 4.2.2 on 2023-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_advantages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityadvantage',
            name='on_hover_icon',
            field=models.ImageField(default='', upload_to='advantages_icons/'),
        ),
    ]
