# Generated by Django 4.2.2 on 2023-06-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer_elements_and_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerelement',
            options={'verbose_name_plural': 'Elements'},
        ),
        migrations.AlterModelOptions(
            name='footerelementcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
