# Generated by Django 4.2.2 on 2023-07-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownNavigationElement1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_dropdown', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Dropdown(1st panel) navigation elements',
            },
        ),
        migrations.CreateModel(
            name='DropdownNavigationElement2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('parent_dropdown_navigation_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header_navigation_elements.dropdownnavigationelement1')),
            ],
            options={
                'verbose_name_plural': 'Dropdown(2nd panel) navigation elements',
            },
        ),
        migrations.CreateModel(
            name='NavigationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_dropdown', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Navigation elements',
            },
        ),
        migrations.CreateModel(
            name='DropdownNavigationElement3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent_dropdown_navigation_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header_navigation_elements.dropdownnavigationelement2')),
            ],
            options={
                'verbose_name_plural': 'Dropdown(3rd panel) navigation elements',
            },
        ),
        migrations.AddField(
            model_name='dropdownnavigationelement1',
            name='parent_navigation_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header_navigation_elements.navigationelement'),
        ),
    ]
