# Generated by Django 4.2.2 on 2023-06-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer_social_networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersocialnetwork',
            options={'verbose_name_plural': 'Social network icon'},
        ),
    ]
