# Generated by Django 4.2.2 on 2023-06-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitu_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_images',
            options={'verbose_name_plural': 'News'},
        ),
    ]
